### ISSUE TITLE
Configuration how to and no access logs

### ISSUE THREAD

**Issue by Firesphere** [firecow/caddy-elastic-encoder#7]
Enabling this encoder does not seem to help in getting logs shipped to Elastic using Filebeat.
Caddy start/stop actions log, but nothing else. No logger actually adds anything.
How do I configure this encoder to write directly to Elastic?

**Comment by Firesphere** [comment]
I got it working from Docker itself, which, obviously, was the whole point.
For those wondering:
using docker compose plugin, add the following:
```
    logging:
      driver: elastic/elastic-logging-plugin:8.17.3
      options:
        hosts: "http://elastichost:9200" # From the HOST perspective
        user: "elastic"
        password: "elasticpassword"
        index: "caddy-%{+yyyy.MM.dd}"
        pipeline: docker-filebeat
```
Pipeline docker-filebeat is a bit stupid name, but this is the pipeline:
```
PUT _ingest/pipeline/docker-filebeat
{
  "processors": [
    {
      "json": {
        "field": "message",
        "add_to_root": true,
        "ignore_failure": true
      }
    }
  ]
}
```
It will parse the `message` object in to a nicely formatted object
